/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rapifood.vistas;

import java.awt.Color;
import java.util.List;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import rapifood.modelo.Conexion;
import rapifood.modelo.Mesa;
import rapifood.modelo.MesaData;

/**
 *
 * @author Fedep
 */
public class AgregarMesa extends javax.swing.JInternalFrame {

    /**
     * Creates new form AgregarMesa
     */
    Conexion con = new Conexion();
    MesaData mesaData = new MesaData(con);
    List<Mesa> mesas = mesaData.obtenerMesas();
    
    public AgregarMesa() {
        initComponents();
    
        int cont=1;
        JButton[] arrBotones = {jbMesa1,jbMesa2,jbMesa3,jbMesa4,jbMesa5,jbMesa6,jbMesa7,jbMesa8,jbMesa9,jbMesa10,jbMesa11,jbMesa12,jbMesa13,jbMesa14,jbMesa15};
        boolean control;
        for(JButton jButton : arrBotones){
            jButton.setName(String.valueOf(cont));
            cont++;
        }
        for(cont=0;cont<arrBotones.length;cont++){
            control=false;
            for (Mesa mesa : mesas){
                if(mesa.getId() == Integer.parseInt(arrBotones[cont].getName())){
                    control=true;
                }
            }
            if(control){
                arrBotones[cont].setBackground(Color.green);
            }
            else{
                arrBotones[cont].setBackground(Color.red);
            }
        }
    }
    
    public void cargarEliminarMesa(JButton boton){
        if(boton.getBackground().equals(Color.green)){
            mesaData.borrarMesa(Integer.parseInt(boton.getName()));
            boton.setBackground(Color.red);
        }
        else if(boton.getBackground().equals(Color.red)){
            Mesa mesa = new Mesa(Integer.parseInt(boton.getName()),4,true);
            mesaData.guardarMesa(mesa);
            boton.setBackground(Color.green);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbMesa1 = new javax.swing.JButton();
        jbMesa2 = new javax.swing.JButton();
        jbMesa3 = new javax.swing.JButton();
        jbMesa4 = new javax.swing.JButton();
        jbMesa5 = new javax.swing.JButton();
        jbMesa6 = new javax.swing.JButton();
        jbMesa7 = new javax.swing.JButton();
        jbMesa8 = new javax.swing.JButton();
        jbMesa9 = new javax.swing.JButton();
        jbMesa10 = new javax.swing.JButton();
        jbMesa11 = new javax.swing.JButton();
        jbMesa12 = new javax.swing.JButton();
        jbMesa13 = new javax.swing.JButton();
        jbMesa14 = new javax.swing.JButton();
        jbMesa15 = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);

        jbMesa1.setText("Mesa 1");
        jbMesa1.setSelected(true);
        jbMesa1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbMesa1ActionPerformed(evt);
            }
        });

        jbMesa2.setText("Mesa 2");
        jbMesa2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbMesa2ActionPerformed(evt);
            }
        });

        jbMesa3.setText("Mesa 3");
        jbMesa3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbMesa3ActionPerformed(evt);
            }
        });

        jbMesa4.setText("Mesa 4");
        jbMesa4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbMesa4ActionPerformed(evt);
            }
        });

        jbMesa5.setText("Mesa 5");
        jbMesa5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbMesa5ActionPerformed(evt);
            }
        });

        jbMesa6.setText("Mesa 6");
        jbMesa6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbMesa6ActionPerformed(evt);
            }
        });

        jbMesa7.setText("Mesa 7");
        jbMesa7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbMesa7ActionPerformed(evt);
            }
        });

        jbMesa8.setText("Mesa 8");
        jbMesa8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbMesa8ActionPerformed(evt);
            }
        });

        jbMesa9.setText("Mesa 9");
        jbMesa9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbMesa9ActionPerformed(evt);
            }
        });

        jbMesa10.setText("Mesa 10");
        jbMesa10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbMesa10ActionPerformed(evt);
            }
        });

        jbMesa11.setText("Mesa 11");
        jbMesa11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbMesa11ActionPerformed(evt);
            }
        });

        jbMesa12.setText("Mesa 12");
        jbMesa12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbMesa12ActionPerformed(evt);
            }
        });

        jbMesa13.setText("Mesa 13");
        jbMesa13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbMesa13ActionPerformed(evt);
            }
        });

        jbMesa14.setText("Mesa 14");
        jbMesa14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbMesa14ActionPerformed(evt);
            }
        });

        jbMesa15.setText("Mesa 15");
        jbMesa15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbMesa15ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jbMesa4)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jbMesa7)
                                        .addGap(18, 18, 18)
                                        .addComponent(jbMesa8))
                                    .addComponent(jbMesa6)))
                            .addComponent(jbMesa9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jbMesa14, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jbMesa15, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbMesa3)
                        .addGap(18, 18, 18)
                        .addComponent(jbMesa5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbMesa13))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addComponent(jbMesa10)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jbMesa1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbMesa2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jbMesa12, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jbMesa11, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbMesa1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbMesa11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbMesa2)
                    .addComponent(jbMesa12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbMesa3)
                    .addComponent(jbMesa5)
                    .addComponent(jbMesa13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbMesa4)
                    .addComponent(jbMesa6)
                    .addComponent(jbMesa14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbMesa7)
                    .addComponent(jbMesa8)
                    .addComponent(jbMesa15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbMesa9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbMesa10)
                .addContainerGap(74, Short.MAX_VALUE))
        );

        jbMesa1.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbMesa1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbMesa1ActionPerformed
       cargarEliminarMesa(jbMesa1);
    }//GEN-LAST:event_jbMesa1ActionPerformed

    private void jbMesa2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbMesa2ActionPerformed
        cargarEliminarMesa(jbMesa2);
    }//GEN-LAST:event_jbMesa2ActionPerformed

    private void jbMesa3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbMesa3ActionPerformed
        cargarEliminarMesa(jbMesa3);
    }//GEN-LAST:event_jbMesa3ActionPerformed

    private void jbMesa4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbMesa4ActionPerformed
        cargarEliminarMesa(jbMesa4);
    }//GEN-LAST:event_jbMesa4ActionPerformed

    private void jbMesa5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbMesa5ActionPerformed
        cargarEliminarMesa(jbMesa5);
    }//GEN-LAST:event_jbMesa5ActionPerformed

    private void jbMesa6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbMesa6ActionPerformed
        cargarEliminarMesa(jbMesa6);
    }//GEN-LAST:event_jbMesa6ActionPerformed

    private void jbMesa7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbMesa7ActionPerformed
        cargarEliminarMesa(jbMesa7);
    }//GEN-LAST:event_jbMesa7ActionPerformed

    private void jbMesa8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbMesa8ActionPerformed
        cargarEliminarMesa(jbMesa8);
    }//GEN-LAST:event_jbMesa8ActionPerformed

    private void jbMesa9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbMesa9ActionPerformed
        cargarEliminarMesa(jbMesa9);
    }//GEN-LAST:event_jbMesa9ActionPerformed

    private void jbMesa10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbMesa10ActionPerformed
        cargarEliminarMesa(jbMesa10);
    }//GEN-LAST:event_jbMesa10ActionPerformed

    private void jbMesa11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbMesa11ActionPerformed
        cargarEliminarMesa(jbMesa11);
    }//GEN-LAST:event_jbMesa11ActionPerformed

    private void jbMesa12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbMesa12ActionPerformed
        cargarEliminarMesa(jbMesa12);
    }//GEN-LAST:event_jbMesa12ActionPerformed

    private void jbMesa13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbMesa13ActionPerformed
        cargarEliminarMesa(jbMesa13);
    }//GEN-LAST:event_jbMesa13ActionPerformed

    private void jbMesa14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbMesa14ActionPerformed
        cargarEliminarMesa(jbMesa14);
    }//GEN-LAST:event_jbMesa14ActionPerformed

    private void jbMesa15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbMesa15ActionPerformed
        cargarEliminarMesa(jbMesa15);
    }//GEN-LAST:event_jbMesa15ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbMesa1;
    private javax.swing.JButton jbMesa10;
    private javax.swing.JButton jbMesa11;
    private javax.swing.JButton jbMesa12;
    private javax.swing.JButton jbMesa13;
    private javax.swing.JButton jbMesa14;
    private javax.swing.JButton jbMesa15;
    private javax.swing.JButton jbMesa2;
    private javax.swing.JButton jbMesa3;
    private javax.swing.JButton jbMesa4;
    private javax.swing.JButton jbMesa5;
    private javax.swing.JButton jbMesa6;
    private javax.swing.JButton jbMesa7;
    private javax.swing.JButton jbMesa8;
    private javax.swing.JButton jbMesa9;
    // End of variables declaration//GEN-END:variables
}
