/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rapifood.vistas;

import javax.swing.JOptionPane;
import rapifood.modelo.Conexion;
import rapifood.modelo.Mesero;
import rapifood.modelo.MeseroData;
import rapifood.vistas.AdministradorLogueado;

/**
 *
 * @author Fedep
 */
public class AgregarMesero extends javax.swing.JFrame {
    
    private Conexion con;
    private MeseroData meseroData;
    
    /**
     * Creates new form PruebaMeseros
     */
    public AgregarMesero() {
        initComponents();
        con = new Conexion();
        meseroData = new MeseroData(con);
    }
    
    private boolean controlCampos(){
        boolean control_nombre=false, control_apellido=false,control_cuit=false,retorno=false;
        if(tfNombre.getText().equals("")){
            control_nombre=true;
        }
        if(tfApellido.getText().equals("")){
            control_apellido=true;
        }
        if(tfCuit.getText().equals("")){
            control_cuit=true;
        }
        if(control_nombre && control_apellido && control_cuit){
            JOptionPane.showMessageDialog(this, "Ingrese nombre,apellido y cuit.");
        }
        else if(control_nombre && !control_apellido && !control_cuit){
            JOptionPane.showMessageDialog(this, "Ingrese nombre");
        }
        else if(!control_nombre && control_apellido && !control_cuit){
            JOptionPane.showMessageDialog(this, "Ingrese apellido");
        }
        else if(!control_nombre && !control_apellido && control_cuit){
            JOptionPane.showMessageDialog(this, "Ingrese cuit");
        }
        else if(control_nombre && control_apellido && !control_cuit){
            JOptionPane.showMessageDialog(this, "Ingrese nombre y apellido");
        }
        else if(control_nombre && !control_apellido && control_cuit){
            JOptionPane.showMessageDialog(this, "Ingrese nombre y cuit");
        }
        else if(!control_nombre && control_apellido && control_cuit){
            JOptionPane.showMessageDialog(this, "Ingrese apellido y cuit");
        }
        else{
            retorno=true;
        }
        return retorno; 
    }
    
    private boolean nombreYaIngresado(){
        boolean retorno=false;
        for(Mesero mesero : meseroData.obtenerMeseros()){
            if(mesero.getNombre().equals(tfNombre.getText()) && mesero.getApellido().equals(tfApellido.getText())){
                retorno=true;
            }
        }
        return retorno;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        tfNombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tfApellido = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tfCuit = new javax.swing.JTextField();
        jbAgregar = new javax.swing.JButton();
        jbBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nombre del mesero");

        tfNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfNombreKeyTyped(evt);
            }
        });

        jLabel2.setText("Apellido del mesero:");

        tfApellido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfApellidoKeyTyped(evt);
            }
        });

        jLabel3.setText("Numero de CUIT:");

        tfCuit.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfCuitKeyTyped(evt);
            }
        });

        jbAgregar.setText("Agregar");
        jbAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAgregarActionPerformed(evt);
            }
        });

        jbBack.setText("Volver al menu");
        jbBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(18, 18, 18)
                                        .addComponent(tfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel3))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(tfApellido)
                                            .addComponent(tfCuit)))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(93, 93, 93)
                                .addComponent(jbAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 48, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jbBack)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tfCuit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addComponent(jbAgregar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 109, Short.MAX_VALUE)
                .addComponent(jbBack)
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfCuitKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfCuitKeyTyped
        char validar = evt.getKeyChar();
        
        if(Character.isLetter(validar)){
            evt.consume();
            JOptionPane.showMessageDialog(rootPane, "Ingrese solo numeros.");
        }
    }//GEN-LAST:event_tfCuitKeyTyped

    private void jbAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAgregarActionPerformed
        if(controlCampos()){
            if(nombreYaIngresado()){
                JOptionPane.showMessageDialog(this, "Ya se ha ingresado un empleado con ese nombre y apellido");
                tfNombre.setText("");
                tfApellido.setText("");
                }
            else{
                boolean control=true;
                String nombre=tfNombre.getText();
                String apellido=tfApellido.getText();
                String cuit=tfCuit.getText();
                for(Mesero mesero : meseroData.obtenerMeseros()){
                    if(mesero.getCuit().equals(tfCuit.getText())){
                        JOptionPane.showMessageDialog(this, "Ya se encuentra un mesero ingresado con ese cuit.");
                        tfCuit.setText("");
                        control=false;
                    }
                }
                if(control){
                    Mesero mesero = new Mesero(apellido,nombre,cuit,true);
                    meseroData.guardarMesero(mesero);
                    JOptionPane.showMessageDialog(this, "Mesero ingresado correctamente.");
                    new AdministradorLogueado().setVisible(true);
                    this.setVisible(false);
                }
            }
        }
    }//GEN-LAST:event_jbAgregarActionPerformed

    private void tfNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfNombreKeyTyped
        char validar = evt.getKeyChar();
        
        if(Character.isDigit(validar)){
            evt.consume();
            JOptionPane.showMessageDialog(rootPane, "Ingrese solo letras.");
        }
    }//GEN-LAST:event_tfNombreKeyTyped

    private void tfApellidoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfApellidoKeyTyped
        char validar = evt.getKeyChar();
        
        if(Character.isDigit(validar)){
            evt.consume();
            JOptionPane.showMessageDialog(rootPane, "Ingrese solo letras.");
        }
    }//GEN-LAST:event_tfApellidoKeyTyped

    private void jbBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBackActionPerformed
        this.setVisible(false);
        new AdministradorLogueado().setVisible(true);
    }//GEN-LAST:event_jbBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgregarMesero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgregarMesero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgregarMesero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgregarMesero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AgregarMesero().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton jbAgregar;
    private javax.swing.JButton jbBack;
    private javax.swing.JTextField tfApellido;
    private javax.swing.JTextField tfCuit;
    private javax.swing.JTextField tfNombre;
    // End of variables declaration//GEN-END:variables
}
