/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rapifood.pruebas;

import rapifood.vistas.IngresoComensal;
import java.util.Calendar;
import java.util.List;
import javax.swing.JButton;
import rapifood.modelo.Conexion;
import rapifood.modelo.Mesa;
import rapifood.modelo.MesaData;
import rapifood.modelo.ReservaData;
import rapifood.modelo.Reserva;

/**
 *
 * @author Fedep
 */
public class PruebaMesa extends javax.swing.JFrame {
    
    private Calendar fechaElegida;
    private final ReservaData reservaData;
    private final Conexion con;
    private final MesaData mesaData;

    /**
     * Creates new form pruebaMesa
     */
    public PruebaMesa() {
        initComponents();
        con = new Conexion();
        reservaData = new ReservaData(con);
        mesaData = new MesaData(con); 
    }
    
    public void setFechaElegida(Calendar fechaElegida){
        this.fechaElegida = fechaElegida;
    }
    
    public void inicializar(){
        JButton[] arrBotones = {jbMesa1,jbMesa2,jbMesa3,jbMesa4,jbMesa5,jbMesa6,jbMesa7,jbMesa8,jbMesa9,jbMesa10,jbMesa11,jbMesa12,jbMesa13,jbMesa14,jbMesa15};
        List<Reserva> reservas = reservaData.obtenerReservas();
        List<Mesa> mesasDisponibles = mesaData.obtenerMesas();
        for(Mesa mesa : mesasDisponibles){
            if(!mesa.isEstado()){
                arrBotones[mesa.getId()-1].setEnabled(false);
            }
        }
        for(Reserva reserva : reservas){
            Calendar fechaRecibida = Calendar.getInstance();
            fechaRecibida.setTime(reserva.getTurno_reserva());
            if(fechaRecibida.getTimeInMillis() == fechaElegida.getTimeInMillis()){
                arrBotones[reserva.getMesa().getId()-1].setEnabled(false);
            }
        }
    }
    
    public void cargarReserva(JButton boton){
        IngresoComensal pruebaIngreso = new IngresoComensal();
        pruebaIngreso.setFechaElegida(fechaElegida);
        pruebaIngreso.setId_mesa(Integer.parseInt(boton.getName()));
        pruebaIngreso.inicializar();
        this.setVisible(false);
        pruebaIngreso.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbMesa1 = new javax.swing.JButton();
        jbMesa2 = new javax.swing.JButton();
        jbMesa3 = new javax.swing.JButton();
        jbMesa4 = new javax.swing.JButton();
        jbMesa5 = new javax.swing.JButton();
        jbMesa6 = new javax.swing.JButton();
        jbMesa7 = new javax.swing.JButton();
        jbMesa8 = new javax.swing.JButton();
        jbMesa9 = new javax.swing.JButton();
        jbMesa10 = new javax.swing.JButton();
        jbMesa11 = new javax.swing.JButton();
        jbMesa12 = new javax.swing.JButton();
        jbMesa13 = new javax.swing.JButton();
        jbMesa14 = new javax.swing.JButton();
        jbMesa15 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jbMesa1.setText("Mesa 1");
        jbMesa1.setName("1"); // NOI18N
        jbMesa1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbMesa1ActionPerformed(evt);
            }
        });

        jbMesa2.setText("Mesa 2");
        jbMesa2.setName("2"); // NOI18N
        jbMesa2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbMesa2ActionPerformed(evt);
            }
        });

        jbMesa3.setText("Mesa 3");
        jbMesa3.setName("3"); // NOI18N
        jbMesa3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbMesa3ActionPerformed(evt);
            }
        });

        jbMesa4.setText("Mesa 4");
        jbMesa4.setName("4"); // NOI18N
        jbMesa4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbMesa4ActionPerformed(evt);
            }
        });

        jbMesa5.setText("Mesa 5");
        jbMesa5.setName("5"); // NOI18N
        jbMesa5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbMesa5ActionPerformed(evt);
            }
        });

        jbMesa6.setText("Mesa 6");
        jbMesa6.setName("6"); // NOI18N
        jbMesa6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbMesa6ActionPerformed(evt);
            }
        });

        jbMesa7.setText("Mesa 7");
        jbMesa7.setName("7"); // NOI18N
        jbMesa7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbMesa7ActionPerformed(evt);
            }
        });

        jbMesa8.setText("Mesa 8");
        jbMesa8.setName("8"); // NOI18N
        jbMesa8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbMesa8ActionPerformed(evt);
            }
        });

        jbMesa9.setText("Mesa 9");
        jbMesa9.setName("9"); // NOI18N
        jbMesa9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbMesa9ActionPerformed(evt);
            }
        });

        jbMesa10.setText("Mesa 10");
        jbMesa10.setName("10"); // NOI18N
        jbMesa10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbMesa10ActionPerformed(evt);
            }
        });

        jbMesa11.setText("Mesa 11");
        jbMesa11.setName("11"); // NOI18N
        jbMesa11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbMesa11ActionPerformed(evt);
            }
        });

        jbMesa12.setText("Mesa 12");
        jbMesa12.setName("12"); // NOI18N
        jbMesa12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbMesa12ActionPerformed(evt);
            }
        });

        jbMesa13.setText("Mesa 13");
        jbMesa13.setName("13"); // NOI18N
        jbMesa13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbMesa13ActionPerformed(evt);
            }
        });

        jbMesa14.setText("Mesa 14");
        jbMesa14.setName("14"); // NOI18N
        jbMesa14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbMesa14ActionPerformed(evt);
            }
        });

        jbMesa15.setText("Mesa 15");
        jbMesa15.setName("15"); // NOI18N
        jbMesa15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbMesa15ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jbMesa4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbMesa1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jbMesa2)
                                .addGap(18, 18, 18)
                                .addComponent(jbMesa3))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jbMesa5)
                                .addGap(18, 18, 18)
                                .addComponent(jbMesa6))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbMesa7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbMesa8, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jbMesa9))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jbMesa10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbMesa11))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jbMesa13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbMesa14)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jbMesa15)
                            .addComponent(jbMesa12))))
                .addContainerGap(157, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbMesa1)
                    .addComponent(jbMesa2)
                    .addComponent(jbMesa3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbMesa4)
                    .addComponent(jbMesa5)
                    .addComponent(jbMesa6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbMesa7)
                    .addComponent(jbMesa8)
                    .addComponent(jbMesa9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbMesa10)
                    .addComponent(jbMesa11)
                    .addComponent(jbMesa12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbMesa13)
                    .addComponent(jbMesa14)
                    .addComponent(jbMesa15))
                .addContainerGap(130, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbMesa1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbMesa1ActionPerformed
        cargarReserva(jbMesa1);
    }//GEN-LAST:event_jbMesa1ActionPerformed

    private void jbMesa2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbMesa2ActionPerformed
        cargarReserva(jbMesa2);
    }//GEN-LAST:event_jbMesa2ActionPerformed

    private void jbMesa3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbMesa3ActionPerformed
        cargarReserva(jbMesa3);
    }//GEN-LAST:event_jbMesa3ActionPerformed

    private void jbMesa4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbMesa4ActionPerformed
        cargarReserva(jbMesa4);
    }//GEN-LAST:event_jbMesa4ActionPerformed

    private void jbMesa5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbMesa5ActionPerformed
        cargarReserva(jbMesa5);
    }//GEN-LAST:event_jbMesa5ActionPerformed

    private void jbMesa6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbMesa6ActionPerformed
        cargarReserva(jbMesa6);
    }//GEN-LAST:event_jbMesa6ActionPerformed

    private void jbMesa7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbMesa7ActionPerformed
        cargarReserva(jbMesa7);
    }//GEN-LAST:event_jbMesa7ActionPerformed

    private void jbMesa8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbMesa8ActionPerformed
        cargarReserva(jbMesa8);
    }//GEN-LAST:event_jbMesa8ActionPerformed

    private void jbMesa9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbMesa9ActionPerformed
        cargarReserva(jbMesa9);
    }//GEN-LAST:event_jbMesa9ActionPerformed

    private void jbMesa10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbMesa10ActionPerformed
        cargarReserva(jbMesa10);
    }//GEN-LAST:event_jbMesa10ActionPerformed

    private void jbMesa11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbMesa11ActionPerformed
        cargarReserva(jbMesa11);
    }//GEN-LAST:event_jbMesa11ActionPerformed

    private void jbMesa12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbMesa12ActionPerformed
        cargarReserva(jbMesa12);
    }//GEN-LAST:event_jbMesa12ActionPerformed

    private void jbMesa13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbMesa13ActionPerformed
        cargarReserva(jbMesa13);
    }//GEN-LAST:event_jbMesa13ActionPerformed

    private void jbMesa14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbMesa14ActionPerformed
        cargarReserva(jbMesa14);
    }//GEN-LAST:event_jbMesa14ActionPerformed

    private void jbMesa15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbMesa15ActionPerformed
        cargarReserva(jbMesa15);
    }//GEN-LAST:event_jbMesa15ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PruebaMesa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PruebaMesa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PruebaMesa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PruebaMesa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PruebaMesa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbMesa1;
    private javax.swing.JButton jbMesa10;
    private javax.swing.JButton jbMesa11;
    private javax.swing.JButton jbMesa12;
    private javax.swing.JButton jbMesa13;
    private javax.swing.JButton jbMesa14;
    private javax.swing.JButton jbMesa15;
    private javax.swing.JButton jbMesa2;
    private javax.swing.JButton jbMesa3;
    private javax.swing.JButton jbMesa4;
    private javax.swing.JButton jbMesa5;
    private javax.swing.JButton jbMesa6;
    private javax.swing.JButton jbMesa7;
    private javax.swing.JButton jbMesa8;
    private javax.swing.JButton jbMesa9;
    // End of variables declaration//GEN-END:variables
}
